# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  # desc "Submit a new Beta Build to Crashlytics Beta"
  # lane :beta do
  #   gradle(task: "clean assembleRelease")
  #   crashlytics
  
  #   # sh "your_script.sh"
  #   # You can also use other beta testing services here
  # end

  desc "Deploy a new version to the Google Play"
  lane :deploy do

    # increment version code
    increment_version_code(
      gradle_file_path: "android/app/build.gradle",
    )
    increment_version_name(
      gradle_file_path: "android/app/build.gradle",
    )

    # Build the release bundle
    gradle(task: "clean assembleRelease")

    # Upload to Google Play
    supply(
      track: 'production',
      aab: 'android/app/build/outputs/bundle/release/app-release.aab',
      rollout: '0.5'
    )
  end
end
